### ISSUE TITLE
can not start hook

### ISSUE THREAD

**Issue by frankenstein91** [terminalnetwork/syncthing-hooks#7]
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GotError: connect ECONNREFUSED ::1:8384
    at onError (/usr/lib/node_modules/syncthing-hooks/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/usr/lib/node_modules/syncthing-hooks/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}

Node.js v18.10.0
```
get this error on start

**Comment by aengl** [comment]
@frankenstein91 That error is the expected behaviour if `syncthing` is not running. Maybe you're running it on a different port?

**Comment by frankenstein91** [comment]
@aengl I use port 8384... not sure if it is default or not

**Comment by aengl** [comment]
That is the default port.

You can check if syncthing is indeed listening to that port by running `lsof -i :8384`, which should list the syncthing process.

**Comment by frankenstein91** [comment]
```
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
syncthing 408 <username>   16u  IPv4  19810      0t0  TCP localhost:8384 (LISTEN)
syncthing 408 <username>   36u  IPv4 192144      0t0  TCP localhost:8384->localhost:58980 (ESTABLISHED)

```

**Comment by aengl** [comment]
Looks like everything is correct on your end, I'll investigate some more on my end 🙂
